sources:
  - name: "Orders Data"
    tables:
      - name: "needful_things.orders"
        columns:
          - "id"
          - "order_datetime"
          - "order_month"
          - "first_name"
          - "last_name"
          - "email"
          - "address"
          - "state"
          - "zipcode"
          - "item"
          - "category"
          - "sales"
          - "channel"
          - "channel_group"
          - "channel_month"